# Generated by Django 5.1.4 on 2025-03-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_food_venue_created_by_venue_datemodified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price_per_unit',
        ),
        migrations.AddField(
            model_name='event',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
